### PR TITLE
fix: useSafeInput hook which is not active when not in raw-mode

### LINKED ISSUE #45: Ink raw mode not supported error when running `game ship` without tty
In a ci environment with no tty the `game ship` command is returning the following error:

```
ERROR Raw mode is not supported on the current process.stdin, which Ink uses
       as input stream by default.
       Read about how to prevent this error on
       https://github.com/vadimdemedes/ink/#israwmodesupported
 - Read about how to prevent this error on
   https://github.com/vadimdemedes/ink/#israwmodesupported
 -handleSetRawM (file:///opt/hostedtoolcache/node/24.4.1/x64/lib/node_modules/s
  ode          hipthis/node_modules/ink/build/components/App.js:108:23)
 - (file:///opt/hostedtoolcache/node/24.4.1/x64/lib/node_modules/shipthis/node_
  modules/ink/build/hooks/use-input.js:36:9)
 -commitHookEffectLis (/opt/hostedtoolcache/node/24.4.1/x64/lib/node_modules/sh
  Mount              ipthis/node_modules/react-reconciler/cjs/react-reconciler.
                     development.js:14817:26)
 -commitPassiveMountO (/opt/hostedtoolcache/node/24.4.1/x64/lib/node_modules/sh
  Fiber              ipthis/node_modules/react-reconciler/cjs/react-reconciler.
                     development.js:16648:11)
 -commitPassiveMountEffec (/opt/hostedtoolcache/node/24.4.1/x64/lib/node_module
  s_complete             s/shipthis/node_modules/react-reconciler/cjs/react-rec
                         onciler.development.js:16608:9)
 -commitPassiveMountEffe (/opt/hostedtoolcache/node/24.4.1/x64/lib/node_modules
  ts_begin              /shipthis/node_modules/react-reconciler/cjs/react-recon
                        ciler.development.js:16595:7)
 -commitPassiveMountE (/opt/hostedtoolcache/node/24.4.1/x64/lib/node_modules/sh
  fects              ipthis/node_modules/react-reconciler/cjs/react-reconciler.
                     development.js:16583:3)
 -flushPassiveEffec (/opt/hostedtoolcache/node/24.4.1/x64/lib/node_modules/ship
  sImpl            this/node_modules/react-reconciler/cjs/react-reconciler.deve
                   lopment.js:19221:3)
 -flushPassiveEff (/opt/hostedtoolcache/node/24.4.1/x64/lib/node_modules/shipth
  cts            is/node_modules/react-reconciler/cjs/react-reconciler.developm
                 ent.js:19166:14)
 - (/opt/hostedtoolcache/node/24.4.1/x64/lib/node_modules/shipthis/node_modules
  /react-reconciler/cjs/react-reconciler.development.js:18951:9)
```

They link to their recommended way to handle this: https://github.com/vadimdemedes/ink/#israwmodesupported

ShipThis version: 0.1.32

### PR DESCRIPTION
**Pull request by madebydavid**
Resolves #45 - also includes changes to fix for #44 which was done in #47

## To test

- `shipthis game wizard android`
- `shipthis game ship`

### CODE REVIEW

**Review by jamiel — APPROVED** [review]

File: src/components/android/ConnectGoogle/index.tsx [hunk 1]
```diff
@@ -42,9 +42,8 @@ const ConnectForGame = ({gameId, helpPage, onComplete, onError, ...boxProps}: Co
     projectId: gameId,
   })
 
-  useInput(async (input) => {
-    const i = input.toLowerCase()
```
Comment (jamiel) [inline src/components/android/ConnectGoogle/index.tsx:46]: @madebydavid isnt this reverting your fix for capital B?

Comment (jamiel) [reply src/components/android/ConnectGoogle/index.tsx:46]: Nevermind seen it being lowered by the caller now.

**Review by jamiel — APPROVED** [review]
